checks:
  method-complexity:
    config:
      threshold: 7
  method-lines:
    config:
      threshold: 30
  method-count:
    config:
      threshold: 25

plugins:
  nodesecurity:
    enabled: true
  git-legal:
    enabled: true
  fixme:
    enabled: true
    config:
      strings:
        - FIXME
        - TODO
  shellcheck:
    enabled: true

ratings:
  paths:
    - "packages/**/*.ts"
exclude_paths:
  - "packages/benchmark/"
  - "packages/**/*.spec.ts"

